/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package waitingroom;

/**
 *
 * @author boroowa
 */


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import waitingroom.utilities.GButton;
import waitingroom.utilities.GInformationContainer;
import waitingroom.utilities.GPlayerIcon;
import waitingroom.utilities.GWaitingRoomGraphics;

/**
 *
 * @author boroowa
 */
public class WaitingRoomPanel extends javax.swing.JPanel {

    /*
     * POLA KLASY
     */
    
    Graphics2D g2d;

    GInformationContainer ginfo;
    
    private GButton button;
    private GButton button2;
    
    private GPlayerIcon playerIcon[];

    
    /**
     * Tworzy ten panel i wylącza go gdy błąd
     */
    public WaitingRoomPanel() {
        super();
        
        //zmienianie wielkości okna
            this.setMaximumSize(new Dimension(800,600));
            this.setMaximumSize(new Dimension(800,600));
        
        //ustawienie layoutu
            setLayout(null);
        
        //wczytywanie danych
            try { loadingInformation(); }
            catch (Exception e) {
                System.out.println("Problem with loading, aborted;");
                System.exit(-1);
            }
        
        //zrobienie ikon graczy
            
            this.playerIcon = new GPlayerIcon[6];
            
            for(int i = 0; i < 3; i++){
                playerIcon[i] = new GPlayerIcon(410, 180 + i * 100, ginfo);
                this.add(playerIcon[i]);
            }
            
            for(int i = 0; i < 3; i++){
                playerIcon[i + 3] = new GPlayerIcon(90, 180 + i * 100, ginfo);
                //playerIcon[i + 3].usingPlace(true);
                //addicomjasndoamnsdoikmaosdmaoisdm
                this.add(playerIcon[i + 3]);
            }

        //dodawanie badziewia na widok
            button = new GButton(490,500, ginfo);
            button2 = new GButton(20, 500, ginfo);
            
            button.setText("Zacznij");
            button2.setText("Cofnij");
        
            this.add(button);
            this.add(button2);
            
    }
    
    /**
     * Wczytuje dane, jeżeli ich nie wyczyta, to wtedy rzuca śliwką
     * @throws Exception 
     */
    private void loadingInformation() throws Exception{
        
        //stworzenie pojemnika na dane
            ginfo = new GInformationContainer();
        
        //wczytujemy fonty
            try{
                ginfo.fonts.setNormalFont("./fonts/D3Euronism.ttf");
                ginfo.fonts.setBoldFont("./fonts/D3Euronism_b.ttf");
                ginfo.fonts.setItalicFont("./fonts/D3Euronism_i.ttf");
            } catch (Exception e) {
                System.out.println("Problem with fonts");
            }
            
        //wczytujemy grafiki dotyczące przycisków
            try{
                ginfo.buttonsGraphics.setGraphics(  "./graphics/MainMenu/unpress_button.png", 
                                                    "./graphics/MainMenu/over_button.png", 
                                                    "./graphics/MainMenu/press_button.png");
            } catch (Exception e) {
                System.out.println("Problem with button graphics");
            }
            
        //wczytujemy grafiki dotyczące przycisków
            try{
                ginfo.playerIconGraphics.setEmptyGraphics("./graphics/WaitingRoomGraphics/grzaczNieaktywowany.png");
                ginfo.playerIconGraphics.setUsedGraphics("./graphics/WaitingRoomGraphics/graczAktywowany.png");
            } catch (Exception e) {
                System.out.println("Problem with player icon graphics");
            }
            
        //wczytujemy pliki potrzebne do wyświetlania okna poczekalni
            
            ginfo.waitingRoomGraphics = new GWaitingRoomGraphics();
            
    }
   
    
    @Override 
    public Dimension getPreferredSize(){
        return new Dimension(800,600);
    }
    
    @Override 
    public Dimension getMinimumSize(){
        return new Dimension(800,600);
    }
    
    @Override 
    public Dimension getMaximumSize(){
        return new Dimension(800,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @Override
    protected void paintComponent(Graphics g) {
        
        //umożliwienie rysowania po powierzchni 2d
            super.paintComponent(g);
            g2d = (Graphics2D) g;
        
            BufferedImage bg = ginfo.waitingRoomGraphics.getBackground();
          
            
            //g2d.drawImage(ginfo.waitingRoomGraphics.img, 100, 100, this);
            
        
        //wczytanie tła
            g2d.drawImage(bg, 0, 0, this);
           
            
         //rysowanie nagłowka
            drawTitle();
            
         //rysowanie centralnego okna
            drawCentralWindow();
        
    }
    
    private void drawCentralWindow(){
        
        for(int i = 0; i < 14; i++){
            g2d.drawImage(ginfo.waitingRoomGraphics.getTopMiddle(), 40 * i + 120, 160, this);
        }  
        
        for(int i = 0; i < 14; i++){
            g2d.drawImage(ginfo.waitingRoomGraphics.getBottomMiddle(), 40 * i + 120, 40 * 6 + 200, this);
        }
        
        for(int i = 0; i < 6; i++){
            g2d.drawImage(ginfo.waitingRoomGraphics.getMiddleLeft(), 80, 40 * i + 200, this);
        }
        
        for(int i = 0; i < 6; i++){
            g2d.drawImage(ginfo.waitingRoomGraphics.getMiddleRight(), 120 + 14 * 40, 40 * i + 200, this);
        }
        
        for(int i = 0; i < 14; i++){
                for(int j = 0; j < 6; j++){
                    g2d.drawImage(ginfo.waitingRoomGraphics.getMiddleMiddle(), 40 * i + 120, 40 * j + 200, this);
                }
           }
        
        g2d.drawImage(ginfo.waitingRoomGraphics.getTopLeft(), 80, 160, this);    
        g2d.drawImage(ginfo.waitingRoomGraphics.getTopRight(), 120 + 40 * 14, 160, this);       
        g2d.drawImage(ginfo.waitingRoomGraphics.getBottomLeft(), 80, 40 * 6 + 200, this);        
        g2d.drawImage(ginfo.waitingRoomGraphics.getBottomRight(), 120 + 40 * 14, 40 * 6 + 200, this);
        
    }
    
    private void drawTitle(){
        
           for(int i = 0; i < 12; i++){
                for(int j = 0; j < 2; j++){
                    g2d.drawImage(ginfo.waitingRoomGraphics.getMiddleMiddle(), 40*i, 40*j, this);
                }
           }
           
           for(int i = 0; i < 12; i++){
               g2d.drawImage(ginfo.waitingRoomGraphics.getBottomMiddle(), 40*i, 40*2, this);
           }
           
           for(int i = 0; i < 2; i++){
               g2d.drawImage(ginfo.waitingRoomGraphics.getMiddleRight(), 40*12, 40*i, this);
           }
           
           g2d.drawImage(ginfo.waitingRoomGraphics.getBottomRight(), 40*12, 40*2, this);
           
           g2d.setFont(ginfo.fonts.getNormal().deriveFont(48.0f));
           g2d.setColor(Color.GREEN);
           g2d.drawString("POCZEKALNIA",20,80);
    }
}
